application: twittmap-xhcyfz
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /gaedatastore
  script: gaedatastore.app
  login: admin

- url: /.*
  script: twittermap.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest

builtins:
- remote_api: on